### ISSUE TITLE
Setting individual terraform rules compared to using terraform plugin with recommended settings

### ISSUE THREAD

**Issue by sthuber90** [globaldatanet/tflint-config#1]
In our tflint config file we specify the 16 terraform rules available, which are:
- terraform_comment_syntax
- **terraform_deprecated_index**
- **terraform_deprecated_interpolation**
- terraform_documented_outputs
- terraform_documented_variables
- **terraform_empty_list_equality**
- **terraform_module_pinned_source**
- **terraform_module_version** 
- terraform_naming_convention
- **terraform_required_providers**
- **terraform_required_version**
- terraform_standard_module_structure
- **terraform_typed_variables**
- **terraform_unused_declarations**
- terraform_unused_required_providers
- **terraform_workspace_remote**

The one marked **bold** are part of the "recommended" presets that can be used with the terraform plugin
``` hcl
plugin "terraform" {
  enabled = true
  preset  = "recommended"
}
```

So why do we set the rules explicitly instead of using the recommended settings with the plugin? Also, should we use the optional  rules that are not part of the recommended preset all the time or should we mark them optional in our tflint configuration as well?

To me using the terraform plugin has a few advantages above defining the rules individually:
1. easier maintenenace: We always follow the recommended ruleset and don't have to regularly update individual rules
2. following best practices: We always follow the recommended ruleset

@mhmdio what's your opinion on this?

**Comment by mhmdio** [comment]
looks nice, we can create separate rules files for each use case? what do you think?
